version: "3"

services:
  mkdocs:
    build:
      context: "./"
      dockerfile: "docker/mkdocs/Dockerfile"
    tty: true
    restart: always
    working_dir: /app
    volumes:
      - $HOME/.ssh/id_rsa:/root/.ssh/id_rsa
      - ./:/app
    ports:
      - "8000:8000"
    command: bash /app/docker/mkdocs/start_dev_server.sh
    environment:
      LIVE_RELOAD_SUPPORT: 'true'
