site_name: 'Ponkan ドキュメント'
site_description: 'Ponkan ドキュメント'
site_author: 'okayu'
copyright: '&copy; 2020 <a href="https://studiomikan.net/ target="_blank">Studio Mikan</a>'
repo_name: 'studiomikan/ponkan-docs'
repo_url: https://github.com/studiomikan/ponkan-docs
edit_uri: ''
theme:
  name: material
  language: 'ja'
  palette:
    primary: deep orange
    accent: 'Deep Orange'
  font:
    text: 'Noto Sans JP'
    code: 'Inconsolata'
  favicon: assets/images/favicon.ico
  icon:
    logo: material/library
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - header.autohide
extra:
  search:
    languaextra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/studiomikan/ponkan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/studiomikan
extra_css:
  - 'exstyle.css'
nav:
  - はじめに: 'index.md'
  - チュートリアル:
    - 開発の準備（セットアップ）: basic/setup.md
    - Node.js導入（Windows）: basic/setup_nodejs_win.md
    - メッセージ（文章）の表示: basic/message.md
    - 画像の表示: basic/image.md
    - レイヤーとページ: basic/layer.md
    - トランジション: basic/trans.md
    - 音声の再生: basic/sound.md
    - 動画の再生: basic/video.md
    - スクリプト間の移動: basic/jump_call.md
    - JavaScriptと変数: basic/javascript.md
    - マクロ機能: basic/macro.md
    - ボタンと条件分岐: basic/fork.md
    - セーブ＆ロード機能: basic/save_and_load.md
    - ゲームを公開する: basic/release.md
  - リファレンス:
    - スクリプトファイル文法: ref/syntax.md
    - コマンドリファレンス: ref/command_ref.md
  - 応用（システム）:
    - コマンドショートカット機能: advanced/command_shortcut.md